### PR TITLE
custom input toggle

### PR DESCRIPTION
**Pull request by gomboskriszta15**

### CODE REVIEW

**Comment by gomboskriszta15** [comment]
@RobertPoienar @ReichEdvin @rucindrea @robert-altom @Dianaserb1

**Review by RobertPoienar — APPROVED** [review]

**Comment by iulianatodoran** [comment]
I connected the game from play mode (AltTester Editor) with Desktop v 1.5.1 to check the functionality of the toggle, and experienced the following behaviors:
- ❗ after deactivating from toggle the `Custom Input` and using `Tap/Swipe` on Desktop, the first input from Desktop is accepted by the game even though it shouldn't and ⬇️ 
- ❗ an error  keeps appearing in the unity console when performing inputs from Desktop and there are serious delays on how the input is handled in the game and Desktop (also in the `Logs` in Desktop there are delays)
```
InvalidOperationException: Sequence contains no matching element
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <1c318258bf0843289b0e2cbe692fee39>:0)
Input.findTouch (System.Int32 fingerId) (at Assets/AltTester/AltServer/Input.cs:1006)
Input+<EndTouch>d__141.MoveNext () (at Assets/AltTester/AltServer/Input.cs:719)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <4746c126b0b54f3b834845974d1a9190>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```
image

**Comment by iulianatodoran** [comment]
Other behavior observed:
- when the `Custom Input` is enabled on `Scene 7 Drag and Drop NIS.unity`, `Scene 7 New Input System Actions.unity`, `Scene 8 Draggable Panel NIP.unity` and `Scene 9 NIS.unity` ❗ clicking on the green popup does not open the Prefab to be able to change settings. The only workaround is to open it from a different scene except the ones mentioned here.

**Review by iulianatodoran — APPROVED** [review]
Approving as the comments were clarified by Kriszta and for the last comment there will be different documentation

**Pull request merged**
