### PR TITLE
853 set keywords in commits messages to run only specific jobs

### PR DESCRIPTION
**Pull request by SandyEma9**

### CODE REVIEW

**Comment by SandyEma9** [comment]
@robert-altom @RobertPoienar @gomboskriszta15 @ReichEdvin

**Comment by robert-altom** [comment]
* If the jobs are cancelled when a new commit is pushed, you can for example to have a job running the python tests and then push a new commit that updates the documentation and the python tests will be canceled. 
* If we change code in the Unity part of the project all tests should run. (e.g. If we change something in `SampleSecens`)
* Now if you change `*.meta` file no tests will run, the same thing happens for Java if you change `pom.xml`.

**Comment by SandyEma9** [comment]
@robert-altom I have resolved the comment

**Comment by RobertPoienar** [comment]
@SandyEma9  In the last commit you modified java file, but the java job was not run. Why?

**Comment by SandyEma9** [comment]
@RobertPoienar I've modify back and now this file appear like never been modified(no difference between this PR and dev for that java file).When I add something different in a Java file than java job will run.In this PR appear modified just yml and a C# file.

**Review by RobertPoienar — APPROVED** [review]

**Review by rucindrea — APPROVED** [review]

**Pull request merged**
