### PR TITLE
Validations for port and host from the AltDialog don't work

### LINKED ISSUE #901: Validations for port and host from the AltUnityDialog don't work
https://gitlab.com/altom/altunity/altunitytester/-/merge_requests/754#note_1109971281 - also this issues

---
<sub>You can find the original issue from GitLab [here](https://gitlab.com/altom/altunity/altunitytester/-/issues/927).</sub>

### PR DESCRIPTION
**Pull request by robert-altom**
Closes #901

### CODE REVIEW

**Comment by robert-altom** [comment]
Ping @RobertPoienar @gomboskriszta15 @ReichEdvin

**Comment by robert-altom** [comment]
This issue removes just the tests related to port forwarding. I'm gonna make another PR to remove the port forwarding options from the AltTester Editor and from the bindings.

**Review by RobertPoienar — CHANGES_REQUESTED** [review]
I'm still reproducing the issue after restarting the connection

**Review by gomboskriszta15 — APPROVED** [review]
👍

**Review by RobertPoienar — APPROVED** [review]
LGTM

**Pull request merged**
