### PR TITLE
1436 concurrency fix bugs listed in test planning

### PR DESCRIPTION
**Pull request by gomboskriszta15**

### CODE REVIEW

**Comment by gomboskriszta15** [comment]
@alttester/developers

**Comment by RobertPoienar** [comment]
image
I get this error when I go to WebGl platform

**Comment by RobertPoienar** [comment]
I don't see implementation for java and python for AltDriver tags

**Comment by iulianatodoran** [comment]
> image I get this error when I go to WebGl platform

A similar problem was described [here](https://github.com/alttester/AltTester-Unity-SDK/issues/1429#issue-1992627108) (available for the oncurrency-feature-branch) but the error is different and in the same script

**Comment by iulianatodoran** [comment]
On Java when I connected a test with specific tags in AltDriver, the specific tags were not parsed when running the test, only the default ones.

- The tags used in the `TestHelper.java` script:
```
public static AltDriver getAltDriver() {
        return new AltDriver("192.168.11.199", TestsHelper.getAltDriverPort(), true, 60, "__default__2", "Android",
                "Android OS 12 / API-31 (SKQ1.210908.001/V13.0.6.0.SFNEUXM)", "637ee113e8de943a538c734003320dac",
                "unknown");
    }
```

- See the logs from AltServer where the tags are the default ones:
image

**Review by rucindrea — APPROVED** [review]

**Review by RobertPoienar — APPROVED** [review]

**Pull request merged**
