### PR TITLE
Fix editor issue with keep define

### PR DESCRIPTION
**Pull request by RobertPoienar**
In this PR I fixed the following issue #1075 #1076 and #1078

### CODE REVIEW

**Comment by rucindrea** [comment]
Looks good once the checks pass.

**Review by rucindrea — APPROVED** [review]

**Comment by iulianatodoran** [comment]
In https://github.com/alttester/AltTester-Unity-SDK/issues/1078, I also mentioned this suggestion "_`it might be helpful to have a tooltip on hovering the setting to give more information on what it is actually useful for`_". When we discussed the issue we concluded that we need more information about the define setting as some users are confused about its purpose and how it is really used. The users are likely to find what they need in the AltTester Editor Window with a tooltip than inside the documentation.

**Comment by iulianatodoran** [comment]
On Mac in Unity the AltTester Editor window has the _Platform_ section empty and there is an error in the console 
image

**Review by iulianatodoran — APPROVED** [review]
LGTM. Should be merged only when the checks pass.

**Pull request merged**
